### ISSUE TITLE
Address picker not working with my rails app

### ISSUE THREAD

**Issue by Akram-Khan** [sgruhier/jquery-addresspicker#10]
I am trying to include address picker in my rails app however it is neither auto completing the address nor giving be the map.

Here is my haml code :- 

```
            %li
                =f.text_field :address, :placeholder => "Address", :id => "addresspicker_map", :class => "custom_textarea"
            %li
                =f.text_field :locality, :id => "locality", :disabled => "true"

            %li
                =f.text_field :country, :id => "country", :disabled => "true"

            %li
                #map
```

This is my jquery :-

$(function() {
            var addresspicker = $( "#addresspicker" ).addresspicker();
            var addresspickerMap = $( "#addresspicker_map" ).addresspicker({
                regionBias: "fr",
              elements: {
                map:      "#map",
                lat:      "#lat",
                lng:      "#lng",
                locality: '#locality',
                country:  '#country'
              }
            });
            var gmarker = addresspickerMap.addresspicker( "marker");
            gmarker.setVisible(true);
            addresspickerMap.addresspicker( "updatePosition");

});

What could be the issue?

Thanks,
Akram

**Comment by Akram-Khan** [comment]
I have posted the question on SO as well, here is the link :- http://stackoverflow.com/questions/10393793/how-to-use-jquery-addresspicker-jquery-with-rails-3-1

**Comment by sgruhier** [comment]
did you include     google maps

<script src="http://maps.google.com/maps/api/js?sensor=false"></script>

and jquery-ui ?

**Comment by Akram-Khan** [comment]
yes I have included both google maps and jquery-ui, I did inspect element to check if both these files are included or not and it was showing both the js files

**Comment by sgruhier** [comment]
could you share an url or give JS errors without that I don't see how I can help.

**Comment by Akram-Khan** [comment]
ok I have pushed the app so that you can have a look at it, here is the link http://quiet-ice-5806.heroku.com/ 

also the address field is the one where I am trying to put the address

**Comment by sgruhier** [comment]
Uncaught ReferenceError: google is not defined
check out JS order, google should be before your application.js

**Comment by Akram-Khan** [comment]
Huh, thanks it worked after changing the order :), please update your answer on SO as well so that I can accept it.

**Comment by sgruhier** [comment]
added
thanks
and great you get it working
