### ISSUE TITLE
Document regionBiais. What's this option for ?

### ISSUE THREAD

**Issue by tristanbes** [sgruhier/jquery-addresspicker#14]
Hi,

Recently in ur commit u added regionBiais. What's the goal of that option ?

**Comment by sgruhier** [comment]
Google will explain it better than me :)

https://developers.google.com/maps/documentation/geocoding/#RegionCodes

**Comment by palodelincak** [comment]
Hello, is possible to limit quering for one country only?

**Comment by sgruhier** [comment]
You can't do that with google but you can limit to a given bounds

https://developers.google.com/maps/documentation/geocoding/#Viewports

the doc says: Note that biasing only prefers results within the bounds; if more relevant results exist outside of these bounds, they may be included

If you are interested by adding that options, please fork and pull a request
Thanks

**Comment by palodelincak** [comment]
Thanks!

**Comment by muirin** [comment]
Well, I'm trying to limit autocomplete hints for one country only (or, at least, to prefer one country) - Poland.

In example - I'm searching for "Kraków". [Cracow, Poland]

I'm typing:
'Kra'
and there are such hints as:
Krae, Tajlandia (Thailand)
Kerang Airport (KRA), Kerang Wiktoria 3579, Australia 

I have to type 'Krakó' to get a proper hint:
Kraków, Polska (Poland)

I just don't need autocompleting with cities from Thailand, USA, France, etc. - i need cities from Poland.

Setting region (http://maps.google.com/maps/api/js?sensor=false&region=pl) or address/bounds influences only on results, not autocomplete hints.

Could you give me any hints?

(sorry for my english :) )
