### ISSUE TITLE
still getting map centered on France after changing regionBias

### ISSUE THREAD

**Issue by mellterm** [sgruhier/jquery-addresspicker#15]
...in 
Ive tried restarting/starting the server, changing how Rails loads the Js files (in-file, in application.html, in assets pipeline).
I am using Rails 3.2. 
I have set regionBias to uk, us, etc....still centers on France.

**Comment by sgruhier** [comment]
I dont understand, map is centered on lat/lng you set. regionBias is used for geocoding

```
    setPosition(new google.maps.LatLng(this.lat.val(), this.lng.val())
```

Could you share your code

**Comment by mellterm** [comment]
I meant more its initial position before the user enters an address and sets the position..
Initially, regionBias is set to "fr" in your code. I tried to change it here to "uk" or "us" but the map still initialized on France.

<pre>

$(function() {
        var addresspickerMap = $( "#addresspicker_map" ).addresspicker({
                                                            regionBias: "fr",
                                                            elements: {
                                                            map: "#map",
                                                            lat: "#location_latitude",
                                                            lng: "#location_longitude",
                                                            locality: '#location_locality',
                                                            country: '#location_country'
                                                            }
}); 
    var gmarker = addresspickerMap.addresspicker( "marker");
    gmarker.setVisible(true);
    addresspickerMap.addresspicker( "updatePosition");
});
</pre>

**Comment by sgruhier** [comment]
you have 2 options:
- set lat / lng in your html input of id #location_latitude and #location_longitude
- set `mapOptions` to any value you want:

``` javascript
var addresspickerMap = $( "#addresspicker_map" ).addresspicker({
  regionBias: "fr",
  mapOptions: {
      zoom: 5, 
      center: new google.maps.LatLng(46, 2), 
      scrollwheel: false,
      mapTypeId: google.maps.MapTypeId.ROADMAP
  },
  elements: {
    map: "#map",
    lat: "#location_latitude",
    lng: "#location_longitude",
    locality: '#location_locality',
    country: '#location_country'
  }
});
```

**Comment by ghost** [comment]
For future reference for others the setting in the map options to center on the USA is: center: new google.maps.LatLng(40.4230, -98.7372),
