### ISSUE TITLE
Autocomplete with only one country.

### ISSUE THREAD

**Issue by dggit** [sgruhier/jquery-addresspicker#19]
Hello,

First of all thanks for your work, really nice !
I wanted to know if there is a way to limit the autocompletion to a list of country ? france/belgium/uk for example.

Thanks in advance

DG

**Comment by sgruhier** [comment]
I dont think you can with google geocoder
If you find a solution please share

**Comment by dggit** [comment]
you have to filter the results in _geocode function
you iterate in result object in order to find type=="country" & shortname==your country code and you only take the one that met this condition

here is my modified function for france adresses, it is a bit dirty but it works 

``` js
// Autocomplete source method: fill its suggests with google geocoder results
    _geocode: function(request, response) {
        var address = request.term, self = this;
        this.geocoder.geocode({
            'address': address + this.options.appendAddressString,
            'region': this.options.regionBias
        }, function(results, status) {
            var fr_results= [];
            if (status == google.maps.GeocoderStatus.OK) {
                for (var i = 0; i < results.length; i++) {
                    results[i].label =  results[i].formatted_address;
                    for (var j = 0; j<results[i].address_components.length; j++)
                    {   
                        //console.log(results[i]);
                        if ((results[i].address_components[j].types[0] =="country") && (results[i].address_components[j].short_name =="FR"))
                        {
                            //console.log(results[i].address_components[j].short_name);
                            results[i].label =  results[i].formatted_address;
                            //fr_results[i] = results[i];
                            fr_results.push(results[i]);
                        }
                    }
                };
            } 
            //console.log(results);
            //console.log(fr_results);
            response(fr_results);
        })
    },
```

**Comment by leccy** [comment]
This is great! But how do I get this to work for UK area? I changed the short_name to UK and GB and can see nothing else in the code that would require to be changed. I've tried other short country names but nothing works except France... am I missing something obvious?

**Comment by leccy** [comment]
I changed the entry to GB over a week ago which produced no results but it seems to be working now. Seems it didn't work instantly but can't understand why :/

**Comment by xurei** [comment]
I made a fork that supports this feature : https://github.com/xurei/jquery-addresspicker

Usage :
$( 'input[name="address"]' ).addresspicker({
        ..., 
        componentsFilter: 'country:BE',
    });

**Comment by sgruhier** [comment]
you should submit a pull request

**Comment by xurei** [comment]
Done already ;-)

**Comment by hugomaiavieira** [comment]
@sgruhier :+1: for this feature. I need.

Is @xurei pull request not ok to be merged?

**Comment by sgruhier** [comment]
I'll do it this week-end
But I can't just merge the PR because code has changed since then and I found few bugs.
But I'll use @xurel code and do it.

**Comment by hugomaiavieira** [comment]
@sgruhier mercy! :smile:

**Comment by xurei** [comment]
@hugomaiavieira yes, it's okay to be merged :-)

**Comment by MichaelBrauner** [comment]
Is it possible to do something like this: 

"componentsFilter": "type:geocode",

?
