### ISSUE TITLE
Using UI Addresspicker inside jquery.bootstrap.wizard

### ISSUE THREAD

**Issue by ditikos** [sgruhier/jquery-addresspicker#31]
When I use the component to the jquery bootstrap wizard, it does not refresh the tiles, instead it shows a large gray area and the first tile. I think it needs a resize event?

**Comment by ditikos** [comment]
Actually I solved it:

On the jquery.ui.addresspicker.js add a new method:

```
updateMap: function () {
    google.maps.event.trigger(this.gmap,"resize");
},
```

And on the tabs onTabShow method add this after initializing the addresspicker:

```
                setTimeout(function() {
                    addresspickerMap.addresspicker( "updateMap" );
                    addresspickerMap.addresspicker( "reloadPosition" );
                    //alert("updated?");
                }, 10); 
```

It needs settimeout because of the loading of the tab, without it it's useless, unless you have something else to contribute :)

**Comment by Mghonz** [comment]
:+1:

**Comment by ghost** [comment]
thank you thank you thank you!. stackoverflow answers didn't help me, you saved my day:)
