### ISSUE TITLE
IE9 + Later JQuery

### ISSUE THREAD

**Issue by shavonn** [sgruhier/jquery-addresspicker#41]
It works great- everywhere except IE9 with a later version of JQuery. 

The demo features 1.4.4 but if I plugin the version of JQuery I am using (1.8.2) and open in ie9, the dropdown stops working.

Any ideas? Works fine in IE10.

**Comment by lemon-pie-now** [comment]
Same issue here with IE8 and 9, any suggestions?

Diana

**Comment by kildem** [comment]
Same issue here with IE10.
fixed: it works on IE10 there was a bug in my code :)
this bug prevented jquery from working only on IE.

**Comment by deneuxa** [comment]
https://github.com/sgruhier/jquery-addresspicker/issues/56
It's work on IE :)

**Comment by deneuxa** [comment]
Problem come from here : 
http://stackoverflow.com/questions/14309037/ajax-no-transport-error-in-ie-8-9

I'm trying to solve this

**Comment by deneuxa** [comment]
This made the trick :D 
https://github.com/MoonScript/jQuery-ajaxTransport-XDomainRequest

**Comment by sgruhier** [comment]
could you post a PR please?

**Comment by deneuxa** [comment]
I did it yet :)
