### ISSUE TITLE
Getting this new error : not allowed by Access-Control-Allow-Origin. 

### ISSUE THREAD

**Issue by deneuxa** [sgruhier/jquery-addresspicker#47]
On my App: 
Origin http://localhost:3000 is not allowed by Access-Control-Allow-Origin. 

With demo files downloaded : 
Origin null is not allowed by Access-Control-Allow-Origin

Has google changed something ? (Maybe a temporary issue from their side)

**Comment by sgruhier** [comment]
I think it's back to normal now
Google temporary issue I guess
Could you confirm?

**Comment by deneuxa** [comment]
yes it is :)

2013/11/7 Sébastien Gruhier notifications@github.com
