### ISSUE TITLE
Places Autocomplete

### ISSUE THREAD

**Issue by Radagaisus** [sgruhier/jquery-addresspicker#5]
The google geocoder isn't meant to do auto complete. E.g. try to write Israel or Brooklyn and it will only suggest those after writing almost the full address. We switched from using it to a mix and match and added Google Places Autocomplete API: http://code.google.com/apis/maps/documentation/places/autocomplete.html

**Comment by sgruhier** [comment]
There is no magick, I just use google maps web service.
Will be great if you can share your mixin with Google Places
