### ISSUE TITLE
How to change the returned value of 

### ISSUE THREAD

**Issue by ajacquot** [sgruhier/jquery-addresspicker#6]
First off thank for this piece of code, it works great!

Here is what I am trying to do: when you pick a location in the auto-complete drop down menu, it fill the input field with selected value, for example, if I am trying to find the Empire State Building in new York, the selected value will end up being: "Empire State Bldg, New York, NY 10001, USA".

I would like instead to have "Empire State Bldg" :i.e. address_components[0].long_name

In your example, I tried to add something like this in _focusAddress: 
    this.addresspicker_map.val(address.address_components[0].long_name);

This works fine to extract address_components[0].long_name to another #id, but does not work to extract it to the main input field.

If this is confusing, here is a site where what I am trying to achieve has been implemented:
http://traveltriangle.com/#search_trips

Any advice will be appreciated.

Thanks.

**Comment by sgruhier** [comment]
Hi
Not sure if address_components[0].long_name is reliable

If you change line 114 from

```
results[i].label = results[i].formatted_address;
```

to
        results[i].label =  results[i].address_components[0].long_name;

doe it work?

**Comment by ajacquot** [comment]
Hey, thanks for taking a look! 

That does not work, because it populates the drop down with address_components[0].long_name... so "Paris, TX" and "Paris, France" are both listed as "Paris" in the drop down... 

I would like the drop down to be populated with formatted_address (as you have by default), but once one of the drop down options is selected, the associated text input field is populated with address_components[0].long_name (in the example above, just "Paris")

**Comment by sgruhier** [comment]
Ah ok I didn't understand. It's pretty easy as jQuery UI can do that
after line 114

``` javascript
  results[i].label =  results[i].formatted_address;
```

just add

``` javascript
  results[i].value = results[i].address_components[0].long_name;
```

jQuery UI will use label for AC text, and value for selected text
May be add a condition to test if  results[i].address_components[0] exists

**Comment by ajacquot** [comment]
Wow! Perfect! Thanks a lot.
