### ISSUE TITLE
Doesn't work on Firefox 12

### ISSUE THREAD

**Issue by deneuxa** [sgruhier/jquery-addresspicker#61]
Autocompletion and drag&drop reverse geocoding don't work on firefox 12

You can find FF 12 here
For Windows : https://www.dropbox.com/s/ar8437tv9as7xxi/Firefox%20Setup%2012.0.exe
MAC OS : https://www.dropbox.com/s/n5hsu0xyigbbfx6/Firefox%2012.0.dmg

**Comment by sgruhier** [comment]
12! Current version is 28.
I cannot test 17 differents versions + subversions on mac/win/unix

**Comment by deneuxa** [comment]
Yeah I know :)
But I had this case on production with some users :/ and just wanted to
report it.

But no worry I'm switching to typeahead, which seems more compatible with
IE old versions and FF old versions too.
I opened some issues there.

2014-04-23 9:02 GMT+02:00 Sébastien Gruhier notifications@github.com:

**Comment by sgruhier** [comment]
I fixed issues you open in typeahead-addresspicker
Thanks for your help in testing.
