### ISSUE TITLE
What if i have to use two markers in the same map??

### ISSUE THREAD

**Issue by girisagar** [sgruhier/jquery-addresspicker#62]

**Comment by kildem** [comment]
:+1: I am interested in more than one marker too.

**Comment by sgruhier** [comment]
To do what exactly? One for the address picker one from something else?

**Comment by kildem** [comment]
This is what I'm trying to do, more than one address picker for the same map:
![schermata 2014-04-24 alle 08 54 23](https://cloud.githubusercontent.com/assets/1815732/2786759/907e906e-cb7d-11e3-8684-afb72e3faf20.png)

**Comment by sgruhier** [comment]
Very interesting
I try to not add new features to jquery-addresspicker since I started [typeahead-addresspicker](https://github.com/sgruhier/typeahead-addresspicker)
If we are intersted, I can try to add that in typeahead-addresspicker
Let me know

**Comment by kildem** [comment]
:+1:  thanks :)
