### ISSUE TITLE
Problem with map inside Jquery Steps

### ISSUE THREAD

**Issue by gelinger777** [sgruhier/jquery-addresspicker#67]
I have an addresspicker in the form which is in Jquery Steps. 

![_22_07_2014_15_20_13](https://cloud.githubusercontent.com/assets/184276/3657253/64b080b8-1192-11e4-9830-af69e8955188.png)

When I resize window the tiles are loaded better. 

Anz hint why that can happen?

**Comment by sgruhier** [comment]
Most of the time, this happens when you instance a google map on a invisible div

**Comment by gelinger777** [comment]
yes I have to init your plugin on the step finished and the div is visible.
