### ISSUE TITLE
Google Places

### ISSUE THREAD

**Issue by alexander-code** [sgruhier/jquery-addresspicker#68]
Hi,

Is there any way or modification to make your library able to search not only addresses but places also?

Thanks in advance

**Comment by sgruhier** [comment]
give a try to https://github.com/sgruhier/typeahead-addresspicker

**Comment by alexander-code** [comment]
Thank you for your reply. I test this demo ( http://sgruhier.github.io/typeahead-addresspicker/ )
but it works only for a specific area. I want a global search for address and places.

**Comment by alexander-code** [comment]
Sorry, not for specific area, I meant only cities, it's not searching for places. Is there any option I have to modify in order to do that? I want to be able to search places and addresses.

**Comment by alexander-code** [comment]
OK, I found it on my own. Thank you.
