### ISSUE TITLE
Small Google Map Marker with two shadows

### ISSUE THREAD

**Issue by rickygu** [sgruhier/jquery-addresspicker#7]
I'm having a weird problem with the Google Map Marker. Everything else is working, except the icon looks weird. When I disable draggableMarker, it become normal again. 

here is an image of what it looks like:
![map](http://i.imgur.com/Eu04M.png)

**Comment by sgruhier** [comment]
how did you disable dragging?
there is a option `draggableMarker: false` on address picker initializer
I tried it on the demo and the marker isn't draggable anymore
could you share code?

**Comment by rickygu** [comment]
I just set draggableMarker to false at line 33 of query.ui.addresspicker.js to disable dragging. 

Here is the code I have for displaying the map and form: 

``` html
<%= content_for(:head) do%>
<script src="http://maps.google.com/maps/api/js?sensor=false"></script>
<% end %>

<script>
    $(function() {
        var addresspickerMap = $( "#addresspicker_map" ).addresspicker({
          elements: {
            map:      "#map",
            lat:      "#lat",
            lng:      "#lng",
            locality: '#locality',
            country:  '#country'
          }
        });
        var gmarker = addresspickerMap.addresspicker( "marker");
        gmarker.setVisible(true);
        addresspickerMap.addresspicker( "updatePosition");
    });
</script>

<p>Make sure the map is pointing your delivery location</p>
<div id='map'></div>

<div class="field">
  <%= f.label :address %><br />
  <%= f.text_field :address, id: "addresspicker_map", class: "ui-autocomplete-input", autocomplete: "off", role: "textbox", :'aria-autocomplete' =>"list", :'aria-haspopup' =>"true" %>
</div>
<div class="field">
  <%= f.label :city %><br />
  <%= f.text_field :city, id: 'locality' %>
</div>
<div class="field">
  <%= f.label :country %><br />
  <%= f.text_field :country, id: 'country' %>
</div>

<%= f.text_field :latitude, id: 'lat', type:'hidden'  %>

<%= f.text_field :longitude, id: 'lng', type: 'hidden' %>
```

**Comment by sgruhier** [comment]
dont touch addresspicker.js 
try 

``` js
        var addresspickerMap = $( "#addresspicker_map" ).addresspicker({
          elements: {
            map:      "#map",
            lat:      "#lat",
            lng:      "#lng",
            locality: '#locality',
            country:  '#country'
          },
          draggableMarker: false
        });

```

**Comment by rickygu** [comment]
that breaks the map. I don't want to disable drag able Marker. I just found that if i disable it, i get the correct looking market.

**Comment by rickygu** [comment]
Ok I think I've pinpointed down the problem. Turns out if I use twitter bootstrap along side jquery ui, it'll mess the map up. Any idea which part of bootstrap may be causing the problem?

**Comment by rickygu** [comment]
ok turns out it's bootstrap's problem with max-width on the image. 

to fix the problem just do 
#map img {
max-width: none;
}

**Comment by sgruhier** [comment]
great you found the issue!
would have been hard for me to solve that !:)

**Comment by IAmKio** [comment]
Thanks! This has solved the issue :+1:
