### ISSUE TITLE
Oops! Something went wrong. This page didn't load Google Maps correctly. See the JavaScript console for technical details.

### ISSUE THREAD

**Issue by mayank-mehrotra** [sgruhier/jquery-addresspicker#75]
Error define itself about the issue but unfortunately no error is showing in the console. Anybody please help why map is not loading. Map is showing during the page load as soon as page load is over then the above error "**This page didn't load Google Maps correctly. See the JavaScript console for technical details.**" show instead of the map and there is no error in the console. Please, help it's urgent. Below check the screenshot:

https://ibb.co/k0kN2v

**Comment by deawx** [comment]
you have include google map api  
please check https://developers.google.com/maps/documentation/javascript/

GET API KEY
