### ISSUE TITLE
auto complete postal code error

### ISSUE THREAD

**Issue by rickygu** [sgruhier/jquery-addresspicker#9]
I'm not sure if this applies to US address, but here in Canada most of the auto complete addresses have wrong postal code (zip code). The user is unable to type in the correct address and type enter, where the only way to trigger the geocoding is to choose one of the incorrect auto complete address.

Would it be possible to geocode without choosing the auto completed address and just press enter or something?

**Comment by sgruhier** [comment]
sorry for the late answer, did you solve that or need help?

**Comment by rickygu** [comment]
hey no worries. I could solve the problem so I ended up using https://github.com/tristandunn/jquery-auto-geocoder for the task. I was able to enter partial addresses without the postal code and it'll still give me a result back.
